# Generated by Django 4.1.2 on 2022-10-13 00:18

from django.db import migrations
from django.contrib.auth.models import Group, User





class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        
    ]
