# Generated by Django 4.1.2 on 2022-11-05 22:09

from django.db import migrations, models
from django.contrib.auth.models import Group, User
from coffee.views import getMenuItemPrice

def populate_db(apps, schema):
    manager_group, createdm = Group.objects.get_or_create(name='Manager')
    customer_group, createdc = Group.objects.get_or_create(name='Customer')
    employee_group, createde = Group.objects.get_or_create(name='Employee')

    manager = User.objects.create_user(username='managerDan', password='imtheboss')
    manager.save()
    manager.groups.add(manager_group)

    employee = User.objects.create_user(username='workerJill', password='ilovetowork')
    employee.save()
    employee.groups.add(employee_group)
    employee.profile.hours_worked = 0.0
    employee.save()
    
    customer = User.objects.create_user(username='personJoe', password='goodpassword')
    customer.save()
    customer.groups.add(customer_group)


    Price_Markup = apps.get_model('coffee', 'Price_Markup')
    Price_Markup.objects.all().delete()

    markup = Price_Markup(markup=43)
    markup.save()

    Menu_Item = apps.get_model('coffee', 'Menu_Item')
    Menu_Item.objects.all().delete()
    Inventory_Item = apps.get_model('coffee', 'Inventory_Item')
    Inventory_Item.objects.all().delete()
    Item_Amount = apps.get_model('coffee', 'Item_Amount')

    i1 = Inventory_Item(name='Milk', quantity=4, price=0.35)
    i1.save()

    i2 = Inventory_Item(name='Ice', quantity=20, price=0.20)
    i2.save()

    i3 = Inventory_Item(name='Vanilla Base', quantity=15, price=1.05)
    i3.save()

    i4 = Inventory_Item(name='Mocha Base', quantity=15, price=1.20)
    i4.save()

    i5 = Inventory_Item(name='Caramel Base', quantity=20, price=1.05)
    i5.save()

    i6 = Inventory_Item(name='Pumpkin Spice Syrup', quantity=10, price=0.50)
    i6.save()

    i7 = Inventory_Item(name='Chocolate Chips', quantity=30, price=0.45)
    i7.save()

    i8 = Inventory_Item(name='Whipped Cream', quantity=20, price=1.00)
    i8.save()

    i9 = Inventory_Item(name='Matcha Powder', quantity=7, price=0.85)
    i9.save()

    i10 = Inventory_Item(name='Cup', quantity=50, price=0.60)
    i10.save()

    i11 = Inventory_Item(name='Strawberry Puree', quantity=30, price=1.20)
    i11.save()

    i12 = Inventory_Item(name='Lids', quantity=50, price=0.50)
    i12.save()

    i13 = Inventory_Item(name='Irish Cream Syrup', quantity=20, price=0.50)
    i13.save()

    i14 = Inventory_Item(name='Half and Half', quantity=20, price=0.40)
    i14.save()

    i15 = Inventory_Item(name='Espresso Shot', quantity=20, price=0.20)
    i15.save()

    i16 = Inventory_Item(name='Chai Tea Base', quantity=50, price=0.60)
    i16.save()

    i17 = Inventory_Item(name='Cinnamon', quantity=50, price=0.10)
    i17.save()

    i18 = Inventory_Item(name='Peppermint', quantity=50, price=0.10)
    i18.save()

    m1 = Menu_Item(name='Caramel Frap')
    m1.save()
    Item_Amount.objects.create(menu_item=m1, inventory_item=i1)
    Item_Amount.objects.create(menu_item=m1, inventory_item=i2, amount=2)
    Item_Amount.objects.create(menu_item=m1, inventory_item=i5)
    Item_Amount.objects.create(menu_item=m1, inventory_item=i12)
    Item_Amount.objects.create(menu_item=m1, inventory_item=i10)
    m1.price = getMenuItemPrice(m1.id)
    m1.save()
    # m1.Ingredients.add(i1, i2, i5, i12, i10)
    # m1.save()
    

    m2 = Menu_Item(name='Mocha Frap')
    m2.save()
    Item_Amount.objects.create(menu_item=m2, inventory_item=i1)
    Item_Amount.objects.create(menu_item=m2, inventory_item=i2, amount=2)
    Item_Amount.objects.create(menu_item=m2, inventory_item=i4)
    Item_Amount.objects.create(menu_item=m2, inventory_item=i8)
    Item_Amount.objects.create(menu_item=m2, inventory_item=i10)
    Item_Amount.objects.create(menu_item=m2, inventory_item=i12)
    m2.price = getMenuItemPrice(m2.id)
    m2.save()
    # m2.Ingredients.add(i1, i2, i4, i8, i12, i10)
    # m2.save()

    m3 = Menu_Item(name='Pink Lady')
    m3.save()
    Item_Amount.objects.create(menu_item=m3, inventory_item=i1)
    Item_Amount.objects.create(menu_item=m3, inventory_item=i2, amount=2)
    Item_Amount.objects.create(menu_item=m3, inventory_item=i3)
    Item_Amount.objects.create(menu_item=m3, inventory_item=i11)
    Item_Amount.objects.create(menu_item=m3, inventory_item=i10)
    Item_Amount.objects.create(menu_item=m3, inventory_item=i12)
    m3.price = getMenuItemPrice(m3.id)
    m3.save()
    # m3.Ingredients.add(i1, i2, i3, i10, i11, i12)
    # m3.save()

    m4 = Menu_Item(name='Gaelic Storm')
    m4.save()
    Item_Amount.objects.create(menu_item=m4, inventory_item=i14, amount=2)
    Item_Amount.objects.create(menu_item=m4, inventory_item=i2)
    Item_Amount.objects.create(menu_item=m4, inventory_item=i13, amount=2)
    Item_Amount.objects.create(menu_item=m4, inventory_item=i15)
    Item_Amount.objects.create(menu_item=m4, inventory_item=i10)
    m4.price = getMenuItemPrice(m4.id)
    m4.save()
    # m4.Ingredients.add(i13, i13, i14, i14, i15, i10)
    # m4.save()

    m5 = Menu_Item(name='Headless Horseman')
    m5.save()
    Item_Amount.objects.create(menu_item=m5, inventory_item=i6)
    Item_Amount.objects.create(menu_item=m5, inventory_item=i17)
    Item_Amount.objects.create(menu_item=m5, inventory_item=i8)
    Item_Amount.objects.create(menu_item=m5, inventory_item=i14)
    Item_Amount.objects.create(menu_item=m5, inventory_item=i15)
    Item_Amount.objects.create(menu_item=m5, inventory_item=i10)
    m5.price = getMenuItemPrice(m5.id)
    m5.save()
    # m5.Ingredients.add(i6, i17, i8, i14, i15, i10)
    # m5.save()

    m6 = Menu_Item(name='TripleX', price=6.50)
    m6.save()
    Item_Amount.objects.create(menu_item=m6, inventory_item=i15, amount=3)
    Item_Amount.objects.create(menu_item=m6, inventory_item=i14)
    Item_Amount.objects.create(menu_item=m6, inventory_item=i3)
    Item_Amount.objects.create(menu_item=m6, inventory_item=i10)
    m6.price = getMenuItemPrice(m6.id)
    m6.save()
    # m6.Ingredients.add(i15, i15, i15, i14, i3, i10)
    # m6.save()

    m7 = Menu_Item(name='Vanilla Ice', price=6.50)
    m7.save()
    Item_Amount.objects.create(menu_item=m7, inventory_item=i3, amount=2)
    Item_Amount.objects.create(menu_item=m7, inventory_item=i2)
    Item_Amount.objects.create(menu_item=m7, inventory_item=i14)
    Item_Amount.objects.create(menu_item=m7, inventory_item=i15)
    Item_Amount.objects.create(menu_item=m7, inventory_item=i10)
    m7.price = getMenuItemPrice(m7.id)
    m7.save()
    # m7.Ingredients.add(i3, i3, i15, i14, i2, i10)
    # m7.save()

    m8 = Menu_Item(name='Chai Lee Latte', price=7.50)
    m8.save()
    Item_Amount.objects.create(menu_item=m8, inventory_item=i16)
    Item_Amount.objects.create(menu_item=m8, inventory_item=i1)
    Item_Amount.objects.create(menu_item=m8, inventory_item=i17)
    Item_Amount.objects.create(menu_item=m8, inventory_item=i14)
    Item_Amount.objects.create(menu_item=m8, inventory_item=i8)
    Item_Amount.objects.create(menu_item=m8, inventory_item=i10)
    m8.price = getMenuItemPrice(m8.id)
    m8.save()
    # m8.Ingredients.add(i16, i1, i17, i14, i8, i10)
    # m8.save()

    m9 = Menu_Item(name='Cocoa Mudslide', price=7.50)
    m9.save()
    Item_Amount.objects.create(menu_item=m9, inventory_item=i4)
    Item_Amount.objects.create(menu_item=m9, inventory_item=i7)
    Item_Amount.objects.create(menu_item=m9, inventory_item=i8)
    Item_Amount.objects.create(menu_item=m9, inventory_item=i14)
    Item_Amount.objects.create(menu_item=m9, inventory_item=i15)
    Item_Amount.objects.create(menu_item=m9, inventory_item=i10)
    m9.price = getMenuItemPrice(m9.id)
    m9.save()
    # m9.Ingredients.add(i15, i4, i7, i14, i8, i10)
    # m9.save()

    m10 = Menu_Item(name='Tis the Season', price=5.50)
    m10.save()
    Item_Amount.objects.create(menu_item=m10, inventory_item=i6)
    Item_Amount.objects.create(menu_item=m10, inventory_item=i17)
    Item_Amount.objects.create(menu_item=m10, inventory_item=i4)
    Item_Amount.objects.create(menu_item=m10, inventory_item=i18)
    Item_Amount.objects.create(menu_item=m10, inventory_item=i15)
    Item_Amount.objects.create(menu_item=m10, inventory_item=i10)
    m10.price = getMenuItemPrice(m10.id)
    m10.save()
    # m10.Ingredients.add(i17, i4, i6, i15, i18, i10)
    # m10.save()

    cm5 = Menu_Item(name='Headless Horseman')
    cm5.save()
    Item_Amount.objects.create(menu_item=cm5, inventory_item=i6)
    Item_Amount.objects.create(menu_item=cm5, inventory_item=i17)
    Item_Amount.objects.create(menu_item=cm5, inventory_item=i8)
    Item_Amount.objects.create(menu_item=cm5, inventory_item=i14)
    Item_Amount.objects.create(menu_item=cm5, inventory_item=i15)
    Item_Amount.objects.create(menu_item=cm5, inventory_item=i10)
    cm5.price = getMenuItemPrice(cm5.id)
    cm5.save()
    cm5.custom = True
    cm5.save()

    cm4 = Menu_Item(name='Gaelic Storm')
    cm4.save()
    Item_Amount.objects.create(menu_item=cm4, inventory_item=i14, amount=2)
    Item_Amount.objects.create(menu_item=cm4, inventory_item=i2)
    Item_Amount.objects.create(menu_item=cm4, inventory_item=i13, amount=2)
    Item_Amount.objects.create(menu_item=cm4, inventory_item=i15)
    Item_Amount.objects.create(menu_item=cm4, inventory_item=i10)
    cm4.price = getMenuItemPrice(cm4.id)
    cm4.save()
    cm4.custom = True
    cm4.save()

    Order = apps.get_model('coffee', 'Order')
    Order.objects.all().delete()

    Profile = apps.get_model('coffee', 'Profile')
    mprofile = Profile.objects.get(id=manager.id)

    anOrder = Order(profile=mprofile, status = 0)
    anOrder.save()
    cm5.order = anOrder
    cm5.save()
    cm4.order = anOrder
    cm4.save()
    anOrder.save()
    
    # anOrder2 = Order(profile=mprofile, status = 1)
    # anOrder2.save()
    # cm5.order = anOrder2
    # cm5.save()
    # cm4.order = anOrder2
    # cm4.save()

    # anOrder3 = Order(profile=mprofile, status = 2)
    # anOrder3.save()
    # cm5.order = anOrder3
    # cm5.save()
    # cm4.order = anOrder3
    # cm4.save()

    # anOrder4 = Order(profile=mprofile, status = 3)
    # anOrder4.save()
    # cm5.order = anOrder4
    # cm5.save()
    # cm4.order = anOrder4
    # cm4.save()

class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_menu_item_custom_alter_item_amount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.RunPython(populate_db)
    ]
