# Generated by Django 4.1.2 on 2022-11-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_alter_menu_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
