# Generated by Django 4.1.2 on 2022-10-21 01:07

from django.db import migrations, models

def populate_db(apps, schema_editor):
    Price_Markup = apps.get_model('coffee', 'Price_Markup')
    Price_Markup.objects.all().delete()

    markup = Price_Markup(markup=0.43)
    markup.save()

class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_drink_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_Markup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RunPython(populate_db),
    ]
