# Generated by Django 4.1.2 on 2022-10-31 15:43

from django.db import migrations, models
import django.db.models.deletion

def populate_db(apps, schema):
    Menu_Item = apps.get_model('coffee', 'Menu_Item')
    Menu_Item.objects.all().delete()
    Inventory_Item = apps.get_model('coffee', 'Inventory_Item')
    Inventory_Item.objects.all().delete()

    i1 = Inventory_Item(name='Milk', quantity=4, price=0.35)
    i1.save()

    i2 = Inventory_Item(name='Ice', quantity=20, price=0.20)
    i2.save()

    i3 = Inventory_Item(name='Vanilla Base', quantity=15, price=1.05)
    i3.save()

    i4 = Inventory_Item(name='Mocha Base', quantity=15, price=1.20)
    i4.save()

    i5 = Inventory_Item(name='Caramel Base', quantity=20, price=1.05)
    i5.save()

    i6 = Inventory_Item(name='Pumpkin Spice Syrup', quantity=10, price=0.50)
    i6.save()

    i7 = Inventory_Item(name='Chocolate Chips', quantity=30, price=0.45)
    i7.save()

    i8 = Inventory_Item(name='Whipped Cream', quantity=20, price=1.00)
    i8.save()

    i9 = Inventory_Item(name='Matcha Powder', quantity=7, price=0.85)
    i9.save()

    i10 = Inventory_Item(name='Cup', quantity=50, price=0.60)
    i10.save()

    i11 = Inventory_Item(name='Strawberry Puree', quantity=30, price=1.20)
    i11.save()

    i12 = Inventory_Item(name='Lids', quantity=50, price=0.50)
    i12.save()

    i13 = Inventory_Item(name='Irish Cream Syrup', quantity=20, price=0.50)
    i13.save()

    i14 = Inventory_Item(name='Half and Half', quantity=20, price=0.40)
    i14.save()

    i15 = Inventory_Item(name='Espresso Shot', quantity=20, price=0.20)
    i15.save()

    i16 = Inventory_Item(name='Chai Tea Base', quantity=50, price=0.60)
    i16.save()

    i17 = Inventory_Item(name='Cinnamon', quantity=50, price=0.10)
    i17.save()

    i18 = Inventory_Item(name='Peppermint', quantity=50, price=0.10)
    i18.save()

    m1 = Menu_Item(name='Caramel Frap', price=6.00)
    m1.save()
    m1.Ingredients.add(i1, i2, i5, i12, i10)

    m2 = Menu_Item(name='Mocha Frap', price=6.00)
    m2.save()
    m2.Ingredients.add(i1, i2, i4, i8, i12, i10)

    m3 = Menu_Item(name='Pink Lady', price=6.00)
    m3.save()
    m3.Ingredients.add(i1, i2, i3, i10, i11, i12)

    m4 = Menu_Item(name='Gaelic Storm', price=7.00)
    m4.save()
    m4.Ingredients.add(i13, i13, i14, i14, i15, i10)

    m5 = Menu_Item(name='Headless Horseman', price=7.00)
    m5.save()
    m5.Ingredients.add(i6, i17, i8, i14, i15, i10)

    m6 = Menu_Item(name='TripleX', price=6.50)
    m6.save()
    m6.Ingredients.add(i15, i15, i15, i14, i3, i10)

    m7 = Menu_Item(name='Vanilla Ice', price=6.50)
    m7.save()
    m7.Ingredients.add(i3, i3, i15, i14, i2, i10)

    m8 = Menu_Item(name='Chai Lee Latte', price=7.50)
    m8.save()
    m8.Ingredients.add(i16, i1, i17, i14, i8, i10)

    m9 = Menu_Item(name='Cocoa Mudslide', price=7.50)
    m9.save()
    m9.Ingredients.add(i15, i4, i7, i14, i8, i10)

    m10 = Menu_Item(name='Tis the Season', price=5.50)
    m10.save()
    m10.Ingredients.add(i17, i4, i6, i15, i18, i10)



class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_alter_profile_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=7.5, max_digits=7)),
                ('Ingredients', models.ManyToManyField(related_name='Inventory_Item', to='coffee.inventory_item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Drink_Item',
        ),
        migrations.AddField(
            model_name='menu_item',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee.order'),
        ),
        migrations.RunPython(populate_db)
    ]
