# Generated by Django 4.1.2 on 2022-10-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_menu_item_order_delete_drink_item_menu_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='Ingredients',
            field=models.ManyToManyField(blank=True, related_name='Inventory_Item', to='coffee.inventory_item'),
        ),
    ]
