# Generated by Django 4.1.2 on 2022-10-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_alter_menu_item_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
