# Generated by Django 4.1.2 on 2022-11-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_remove_order_paid_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='Ingredients',
            field=models.ManyToManyField(blank=True, related_name='inventory_items', to='coffee.inventory_item'),
        ),
        migrations.CreateModel(
            name='Item_Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_amounts', to='coffee.inventory_item')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_amounts', to='coffee.menu_item')),
            ],
        ),
    ]
