# Generated by Django 4.0.2 on 2022-11-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_remove_order_paid_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='Ingredients',
            field=models.ManyToManyField(blank=True, related_name='Inventory_Item', to='coffee.Inventory_Item'),
        ),
    ]
